vendor: IntoVPSC Cloud
name: Kubernetes Container Service
version: 1.17.17
website_url: https://intovps.com/kubernetes.html
documentation_url: https://intovps.com/docs/kubernetes/
product_logo_url: https://intovps.com/assets/img/logo_intovps.svg
type: hosted
description: Fully managed Kubernetes fully integrated with OpenStack
